### ISSUE TITLE
A_Note_About_Wallet_Backups.txt is out of date

### ISSUE THREAD

**Issue by jeroz1** [hans-schmidt/mastering_ravencoin#1]
The new core wallet will default to type 3 in mastering_ravencoin/reference/A_Note_About_Wallet_Backups.txt

**Comment by hans-schmidt** [comment]
Thanks for the reminder. I removed this file and replaced it with a much more informative file at https://hans-schmidt.github.io/mastering_ravencoin/analysis/Wallet_Features_and_Problems_in_the_Ravencoin_C-Plus-Plus_Node.html
